/* Copyright 2025 Research Organization for Information Science and Technology */
/*--------------------------------------------------------------------*/
/* diffuse

   MOLECULAR DYNAMICS METHOD FOR MOLECULAR DIFFUSION PROBLEM

   Author: Yukihiro Ota (yota@rist.or.jp)
   Last update: 29 July 2017

   The original code is taken from a textbook,
   A. Sato, Introduction to Molecular simulation with sample
   simulation programs (in Japanese) (Kyouritsu, 2004) 3.1.6

   The temporal evolution is generated by a simple 
   Verlet algorithm. 
   If you want to know a more sophisticate method, you can 
   find it on, e.g.,
   PIMD
   http://ccse.jaea.go.jp/ja/download/pimd/index.jp.html
 
   Masataka Nagaoka (ed.)
   An Easy Guide to Molecular Simulations (Kodansha,2008)
   (in Japanese)

   Also, you can find more advanced techniques in some 
   Japanese textbooks:
   S. Okazaki and N. Yoshii (Kagaku Doujin, 2000) Chap.6

                                                                      */
/*--------------------------------------------------------------------*/
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include "setup.h"
#include "message.h"
#include "rndvar.h"
#include "calc.h"

int main ( int argc, char **argv )
{
  /*------------------------------------------------------------------*/
  /* local variables                                                  */
  /*------------------------------------------------------------------*/
  InputData model;  /* model parameter set */
  AtomData  atom;   /* atom information    */

  /*------------------------------------------------------------------*/
  /* check arguments                                                  */
  /*------------------------------------------------------------------*/
  if ( argc < 2 ) {
    message_of_usage ();
    return EXIT_SUCCESS;
  }

  /*------------------------------------------------------------------*/
  /* initialize simulation                                            */
  /*------------------------------------------------------------------*/
  /* read input parameters */ 
  if (  read_input ( &model ) != 0 ) {
    message_of_usage ();
    message_of_abtermination (); 
    return EXIT_FAILURE;
  }

  /* calculate parameters */
  set_iparam ( &model );

  /* check test mode */
  if ( model.iflag_test == 0 ) {
    message_of_testmode( &model );
    return EXIT_SUCCESS;
  }
  /* memory allocation */
  AtomData_Init ( &atom );
  AtomData_Get_Mem ( &atom, &model );

  /* create array of mass */
  calc_mass ( &model, &atom );

  /* write down header part of simulation log */
  message_of_header ();
  message_of_rephinp ( &model );
  message_of_calcparam ( &model );
  message_of_output ();

  /*------------------------------------------------------------------*/
  /* generate initial configuration                                   */
  /*------------------------------------------------------------------*/
  /* set a seed of random numbers */
  {
    int is=0; /* default seed: 5489UL */
    //int is=1; /* from system time */
    set_rndseed ( &is );
  }

  /* set initial position and velocity */
  {
    int ndeg=3*model.num_partot;
    /* position */
    if ( calc_iniposit(ndeg, &model, &atom) < 0 ) {
      message_of_abtermination ();
      AtomData_Free_Mem ( &atom );
      return EXIT_FAILURE;
    }
    /* velocity */
    calc_inivel(ndeg, &model, &atom);
  }
  
  /* calculate 1st step */
  calc_force ( &model, &atom, atom.rx0, atom.ry0, atom.rz0); 
#ifdef __DIFFUSE__
  calc_positr1_diffuse ( &model, &atom, atom.rx0, atom.ry0, atom.rz0,
		  atom.rx, atom.ry, atom.rz); 
#else
  calc_positr1 ( &model, &atom, atom.rx0, atom.ry0, atom.rz0,
		  atom.rx, atom.ry, atom.rz); 
#endif

  /* write initial configuration */
  {
    FILE *fp;
    char *filename="./inigeom.xyz";
    fp=fopen(filename,"w");
    write_output_pos (fp,&model,atom.rx0,atom.ry0,atom.rz0);
    fclose(fp); 
  }

  /*------------------------------------------------------------------*/
  /*  main loop                                                       */
  /*------------------------------------------------------------------*/ 
  {
    FILE *fp;
    char *filename = "trj.xyz";
    fp = fopen(filename,"w");
    write_output_pos (fp,&model,atom.rx0,atom.ry0,atom.rz0);
   
    for ( int it=1; it <= model.nstep; it=it+1 ) { /* loop on it */
#ifdef __DIFFUSE__
      calc_force_diffuse ( &model, &atom, atom.rx, atom.ry, atom.rz); 
      calc_positr_diffuse ( &model, &atom, atom.rx0, atom.ry0, atom.rz0,
		  atom.rx, atom.ry, atom.rz); 

      /* write position */
      if ( (it % model.nobs) == 0 ) {
        write_output_pos (fp,&model,atom.rx,atom.ry,atom.rz);
      } 
#else
      calc_force ( &model, &atom, atom.rx, atom.ry, atom.rz); 
      calc_positr ( &model, &atom, atom.rx0, atom.ry0, atom.rz0,
		  atom.rx, atom.ry, atom.rz); 

      /* write position */
      if ( (it % model.nobs) == 0 ) {
        write_output_pos (fp,&model,atom.rx,atom.ry,atom.rz);
      } 
#endif
    } /* End of loop on it */
    fclose(fp);
  }

  /*------------------------------------------------------------------*/
  /* finalize simulation                                              */
  /*------------------------------------------------------------------*/ 
  AtomData_Free_Mem ( &atom );

  printf("*** The program is normally finished ***");

  return EXIT_SUCCESS; 
}
