/* Copyright 2024 Research Organization for Information Science and Technology */
/*--------------------------------------------------------------------*/
/* rndvar.c                                                            
   Author: Yukihiro Ota (yota@rist.or.jp)                            
   Last update: 29 July 2017                                          */
/*--------------------------------------------------------------------*/
#include <time.h>
#include <math.h>
#include "common.h"
#include "rndvar.h"

/*--------------------------------------------------------------------*/
/*  set_rndseed
    Initialization of pseudorandom variables generated by the MT method
    See
       www.math.sci.hiroshima-u.ac.jp/~m-mat/MT/mt.html
       www001.upp.so-net.ne.jp/isaku/rand.html

    Any nonzero 32-bit integer can be used as a seed
    After calling this routine, genrand_real1() generates one  
    pseudorandom real number (double), uniformly distributed 
    on [0,1] interval                                                 */
/*--------------------------------------------------------------------*/
void set_rndseed ( int *irnd )
{
  if ( *irnd > 0 ) {
    init_genrand((unsigned) time(NULL));
  } else {
    /* debug mode: 5489UL is the default seed */   
    init_genrand(5489UL);
  }
  return;
}
/*--------------------------------------------------------------------*/
/* get_rnd_array                                                      */
/*--------------------------------------------------------------------*/
void get_rnd_array( int *n, double rd[] )
{
  for ( int i=0; i<*n; i=i+1 ) {
    rd[i] =  genrand_real1();
  }
  return;
}
/*--------------------------------------------------------------------*/
/* get_rnd_array_for_BM                                               */
/*--------------------------------------------------------------------*/
void get_rnd_array_for_BM ( int *n, double rdx[], double rdy[] )
{

  int iset;
  double v;

  for ( int i=0; i<*n; i=i+1) {
    /* generate two uniform random variables in [0,1] */
    iset=0;
    while ( iset == 0 ){
      v = genrand_real1();
      /* to avoid problematic behavior in BM transformation */
      if ( v > 1.0e-6 ) {
        rdx[i]=v;
        iset=1; 
      } 
    }
    rdy[i]=genrand_real1();
  }
  return;
}	
/*--------------------------------------------------------------------*/
/* Box-Mueller transformation
   
   D. U. Lee, J. D. Villasenor, W. Luk, and P. H. W. Leong,
   A hardware Gaussian noise generator using Box-Mueller method
   and its error analysis
   IEEE Transactions on Computers, Vol.55-6 pp.659-671 (2006).

   This code is made, according to a Japanese textbook written by
   Tetsuaki Yotsuji (2010, www.pleiades-publishing.co.jp).

   This is the most primitive (and simplest) generator of Gaussian
   white noise from two uniform random variables                      */
/*--------------------------------------------------------------------*/
double boxmueller( int *irnd, double *rdx, double *rdy, 
		double *sigma )
{
  static int iset;
  int itmp1,itmp2;
  double wx,wy;

  /* initialization of iset */
  if ( *irnd == 1 ) {
    iset=1;
    *irnd=0;
    return 0.0;
  } 

  /* Box-Mueller transformation */
  /* x and y are two uniform random variables in [0,1] */
  wx = sqrt(-2.0*log((*rdx)))*cos((*rdy)*DPI);
  wy = sqrt(-2.0*log((*rdx)))*sin((*rdy)*DPI);

  /* Gaussian random variable with variant sigma^2 */
  /* wx and wy are taken with an alternative manner */
  wx = ((double)iset)*wx + ((double)(iset-1))*wy;
  wx = (*sigma)*wx;

  /* for the next calculation */
  itmp1 = iset+1;
  itmp2 = itmp1/2;
  iset = itmp1 - itmp2*2;

  return wx;
}