# Intel oneAPI 2022.3.1
CXX=icpx
CXXFLAGS=-g -O2 -fopenmp #-DWO_CRITICAL or -DBETTER_IMPL
LIB=

EXE=run.x
OBJS=myclass.o main.o

.SUFFIXES: .cpp .o

$(EXE): $(OBJS)
	$(CXX) $(CXXFLAGS) $(OBJS) $(LIB) -o $@

.cpp.o:
	$(CXX) $(CXXFLAGS) -c $< -o $@

main.o: myclass.o main.cpp

myclass.o: myclass.cpp

.PHONY:
clean:
	rm -f *.o $(EXE)
