## Apple clang 15.0.0
CXX=clang++
CXXFLAGS=-g -O2 #-DWO_CRITICAL or -DBETTER_IMPL

OMP_ROOT = # Please specify the location of your installed libomp.
INC = -I$(OMP_ROOT)/include
LIB = -L$(OMP_ROOT)/lib -lomp
CXXFLAGS += -Xclang -fopenmp $(INC)

EXE=run.x
OBJS=myclass.o main.o

.SUFFIXES: .cpp .o

$(EXE): $(OBJS)
	$(CXX) $(CXXFLAGS) $(OBJS) $(LIB) -o $@

.cpp.o:
	$(CXX) $(CXXFLAGS) -c $< -o $@

main.o: myclass.o main.cpp

myclass.o: myclass.cpp

.PHONY: clean
clean:
	rm -f *.o $(EXE)
