# Xeon(IceLake)+A100 with Nvidia HPC SDK 23.11
CUDA_ROOT= # specify the path if necessary.
CC=nvc
CCFLAGS=-g -c11 -fast -tp=icelake -acc=gpu -gpu=cc80,cuda12.3,pinned -Minfo=accel #-cudalib=nvtx3
INC=-DUSE_NVTX #-I$(CUDA_ROOT)/include
LIB=-lm

CCFLAGS += $(INC)

.SUFFIXES: .c .o

EXE=run.x

OBJS= main.o

$(EXE): $(OBJS)
	$(CC) $(CCFLAGS) $(OBJS) $(LIB) -o $(EXE)

main.o: main.c

.c.o:
	$(CC) $(CCFLAGS) -c $< -o $@

.PHONY:
clean:
	rm -f *.o $(EXE)
