# Xeon(IceLake)+A100 with Nvidia HPC SDK 23.11
CC=nvc
CCFLAGS=-g -c11 -fast -mp=multicore -acc=multicore -tp=icelake -Minfo=accel,mp
LIB=-lm

.SUFFIXES: .c .o

EXE=run.x

OBJS= main.o memory.o timer.o

$(EXE): $(OBJS)
	$(CC) $(CCFLAGS) $(OBJS) $(LIB) -o $(EXE)

main.o: memory.o main.c

memory.o: memory.c

timer.o: timer.c

.c.o:
	$(CC) $(CCFLAGS) -c $< -o $@

.PHONY:
clean:
	rm -f *.o $(EXE)
