# Intel DPC/C++ (oneAPI 2022.3.1)
CC=icx
CFLAGS=-g -Wall -std=gnu99 -O0 #-DNOT_USE_GNULOC
##########################################################################
SRC= \
     main.c mykernel.c

OBJS = \
       $(SRC:.c=.o)

.SUFFIXES: .c .o

run.x: $(OBJS)
	$(CC) $(CFLAGS) $(OBJS) $(LIB) -o $@

.c.o:
	$(CC) $(CFLAGS) -c $< -o $@ $(LIB)

main.o: mykernel.o main.c

mykernel.: mykernel.c

.PHONY: clean
clean:
	rm -f *.o *~

.PHONY: veryclean
veryclean: clean
	rm -f *.x

