## Intel DPC++/C++ (Intel oneAPI 2022.3.1)
CC=icx
CFLAGS=-g -Wall -O0 -std=c11 
INCPATH=
LIBPATH=
LIB=
###########################################################################
SRC= \
     main.c

OBJS = \
       $(SRC:.c=.o)

.SUFFIXES: .o .c

run.x: main.o
	$(CC) $(CFLAGS) $(INCPATH) $(LIBPATH) $(OBJS) $(LIB) -o $@

.c.o:
	$(CC) $(CFLAGS) -c $< -o $@

main.o: main.c		

.PHONY: clean
clean:
	rm -f *.o *~

.PHONY: veryclean
veryclean: clean
	rm -f *.x

