## Intel oneAPI 2022.3.1
CC=icx
CFLAGS=-g -Wall -std=gnu99 -O3 -fopenmp
LIB=
INC=
#

.SUFFIXES: .o .c

all: run.x

run.x: mykernel.o main.o
	$(CC) $(CFLAGS) $(INC) mykernel.o main.o $(LIB) -o $@	

main.o: main.c

mykernel.o: mykernel.c

.c.o:
	$(CC) $(CFLAGS) -c $< -o $@

.PHONY:
clean:
	rm -f *~ *.o *.x
