! Copyright 2025 Research Organization for Information Science and Technology
!!$---------------------------------------------------------------------
!!$ diffuse
!!$
!!$ MOLECULAR DYNAMICS METHOD FOR MOLECULAR DIFFUSION PROBLEM
!!$
!!$ Author: Yukihiro Ota (yota@rist.or.jp)
!!$ Last update: 1 Nov 2016
!!$
!!$ The original code is taken from a textbook,
!!$ A. Sato, Introduction to Molecular simulation with sample
!!$ simulation programs (in Japanese) (Kyouritsu, 2004) 3.1.6
!!$
!!$ The temporal evolution is generated by a simple 
!!$ Verlet algorithm. 
!!$ If you want to know a more sophisticated method, you can 
!!$ find it on, e.g.,
!!$  PIMD
!!$  http://ccse.jaea.go.jp/ja/download/pimd/index.jp.html
!!$ 
!!$  Masataka Nagaoka (ed.)
!!$  An Easy Guide to Molecular Simulations (Kodansha,2008)
!!$ (in Japanese)
!!$
!!$ Also, you can find more advanced techniques in some 
!!$ Japanese textbooks:
!!$  S. Okazaki and N. Yoshii (Kagaku Doujin, 2000) Chap.6
!!$
!!$  
!!$---------------------------------------------------------------------

program main

  use common_par,only: num_partot,nstep, nobs, iflag_test, &
       unit_gen_inp,unit_gen_out,unit_std_out

  use common_var,only: get_memory_of_array, &
       del_memory_of_array,rx0,ry0,rz0,rx,ry,rz
  
  implicit none

  !!-------------------------------------------------------------------
  !! /* local variables */
  !!-------------------------------------------------------------------
  integer :: icon
  integer :: it
  integer :: NRD
  character(len=32) :: inpfn

  !!-------------------------------------------------------------------
  !! /* initialize simulation */
  !!-------------------------------------------------------------------
  icon = 0

  !! read input file 
  call chk_input(icon,inpfn)
  if ( icon .ne. 0 ) then
     if ( icon .lt. 0 ) then
        call message_of_abtermination
     else
        write(unit_std_out,'(A)') &
             "*** The simulation is normally finalized ***"
     end if
     stop
  end if

  open(unit_gen_inp,file=inpfn)
  call read_input(icon,unit_gen_inp)
  close(unit_gen_inp)
  if ( icon .lt. 0 ) then
     call message_of_abtermination
     stop
  end if

  call calc_param

  if ( iflag_test .eq. 0 ) then
     call message_of_testmode
     stop
  end if

  !! memory allocation
  call get_memory_of_array
  
  !! create array of mass 
  call calc_mass
 
  !! write down header part of log 
  call message_of_header
  call message_of_rephinp
  call message_of_calcparam
  call message_of_output

  !!-------------------------------------------------------------------
  !! /* generate initial configuration */
  !!-------------------------------------------------------------------
  !! set a random-number seed
  icon=0  !! seed is a default value, 4357
  !icon = 2 !! seed is determined by the system clock
  call set_rndseed(icon)
  
  !! set initial position and velocity
  NRD = 3*num_partot
  call calc_iniposit(icon,NRD)
  if ( icon .lt. 0 ) then
     call message_of_abtermination
     call del_memory_of_array
     stop
  end if

  call calc_inivel(icon,NRD,num_partot)

  !! calculate 1st step
  call calc_force(num_partot,rx0,ry0,rz0)
#ifdef _DIFFUSE
  call calc_positr1_diffuse(num_partot,rx0,ry0,rz0,rx,ry,rz)
#else
  call calc_positr1(num_partot,rx0,ry0,rz0,rx,ry,rz)
#endif

  !! write initial configuration
  open(unit_gen_out,file="inigeom.xyz",status="replace")
  call write_output_pos(unit_gen_out,num_partot,rx0,ry0,rz0)
  close(unit_gen_out)

  !!-------------------------------------------------------------------
  !! /* main loop */
  !!-------------------------------------------------------------------
  open(unit_gen_out,file="trj.xyz",status="replace")
  call write_output_pos(unit_gen_out,num_partot,rx0,ry0,rz0)

  loopit: do it = 1, nstep
     
#ifdef _DIFFUSE
     call calc_force_diffuse(num_partot,rx,ry,rz)
     call calc_positr_diffuse(num_partot,rx0,ry0,rz0,rx,ry,rz)
     
     !! write position
     if ( mod(it,nobs) .eq. 0 ) then
        call write_output_pos(unit_gen_out,num_partot,rx,ry,rz)
     end if
#else
     call calc_force(num_partot,rx,ry,rz)
     call calc_positr(num_partot,rx0,ry0,rz0,rx,ry,rz)

     !! write position
     if ( mod(it,nobs) .eq. 0 ) then
        call write_output_pos(unit_gen_out,num_partot,rx,ry,rz)
     end if
#endif
     
  end do loopit
  close(unit_gen_out)

  !!-------------------------------------------------------------------
  !! /* finalize simulation */
  !!-------------------------------------------------------------------
  call del_memory_of_array

  write(unit_std_out,'(A)') "*** The program is normally finished ***"

  stop
end program main

