## Intel oneAPI 2022.3.1
CC=icx
DFLAGS := $(DFLAGS)
#DFLAGS := -DNOT_USE_MASKED 
CFLAGS=-g -fopenmp -O0 $(DFLAGS)

.SUFFIXES: .c .o

SRC=main.c

run.x: main.o
	$(CC) $(CFLAGS) main.o -o $@ 

.c.o:
	$(CC) $(CFLAGS) -c $< -o  $@ 

main.o: main.c

.PHONY:
clean:
	rm -f *.o run.x
