## Apple clang 15.0.0
CC = clang
DFLAGS := $(DFLAGS)
#DFLAGS := -DNOT_USE_MASKED # if your libomp does not support masked
CFLAGS = -g -O0 $(DFLAGS)

OMP_ROOT = # Please specify the location of your installed libomp.
INC = -I$(OMP_ROOT)/include
LIB = -L$(OMP_ROOT)/lib -lomp
CFLAGS += -Xclang -fopenmp $(INC)

.SUFFIXES: .c .o

SRC=main.c

run.x: main.o
	$(CC) $(CFLAGS) main.o $(LIB) -o $@ 

.c.o:
	$(CC) $(CFLAGS) -c $< -o  $@ 

main.o: main.c

.PHONY: clean
clean:
	rm -f *.o run.x
