## Apple clang 15.0.0
CC=clang++
CCFLAGS=-g -Wall -std=c++11 -O0
############################
SRC= \
	main.cc

OBJ=$(SRC:.cc=.o)

.SUFFIXES: .cc .o

run.x: $(OBJ) 
	$(CC) $(CCFLAGS) $(OBJ) -o run.x

.cc.o:
	$(CC) $(CCFLAGS) -c $< -o $@

main.o: main.cc

.PHONY: clean
clean:
	rm -f *.cc~ *.o *.mod

.PHONY: veryclean
veryclean: clean
	rm -f *.x
